### ISSUE TITLE
Starting, Then Closing

### ISSUE THREAD

**Issue by G00Dway** [MathInDOS/CmdDraw#2]
Heya Lily! Its Me G00Dway, So The Problem Is, When i ran the program on (Virtual Machine) - Windows 10 - It Starts But After 2-5 Minutes It Just Closes, I Dont Know Why :(

**Comment by MathInDOS** [comment]
It's actually a console drawer as Windows 10 terminal doesn't support old legacy GDI objects it have issues to run on win10. Better run on 8 or 8.1 or lower. (btw it's deprecated and will not maintain ik future).
